name: system_shortcuts
description: ANDROID & IOS flutter plugin to use system shortcuts like pressing home, back, volume Up, volume Down keys and toggle wifi, and bluetooth as well. 
version: 1.0.1
homepage: https://github.com/aman-malhotra-1999/SystemShortcutsFlutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter_sdk: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.systemshortcuts
        pluginClass: SystemShortcutsPlugin
      ios:
        pluginClass: SystemShortcutsPlugin

